-- ============================================================================
-- SQL de monetização — Planejamento de Aula SESI
-- Cole este script no: Supabase Dashboard > SQL Editor > New query > Run.
-- Rode ANTES de publicar a versão monetizada.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- 1) Perfis (1 perfil por usuário do Supabase Auth)
--    Guarda chave Groq do próprio professor, modelo e saldo de créditos.
-- ---------------------------------------------------------------------------
create table if not exists public.perfis (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade unique,
  nome text not null default '',
  unidade text not null default '',
  groq_api_key text not null default '',
  groq_model text not null default 'openai/gpt-oss-120b',
  credito_inicial integer not null default 15,
  is_admin boolean not null default false,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- 2) Catálogo de pacotes de créditos vendáveis
-- ---------------------------------------------------------------------------
create table if not exists public.planos (
  id bigint generated by default as identity primary key,
  nome text not null,
  creditos integer not null,
  preco_centavos integer not null,
  destaque boolean not null default false,
  ativo boolean not null default true,
  ordem integer not null default 0
);

-- Pacotes sugeridos (ajuste preços conforme desejar)
insert into public.planos (nome, creditos, preco_centavos, destaque, ativo, ordem) values
  ('Básico',      50,  1500,  false, true, 1),
  ('Popular',    150,  3900,  true,  true, 2),
  ('Completo',   400,  9000,  false, true, 3)
on conflict do nothing;

-- ---------------------------------------------------------------------------
-- 3) Transações de crédito (toda movimentação fica registrada)
-- ---------------------------------------------------------------------------
create table if not exists public.credito_transacoes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  tipo text not null check (tipo in ('bonus','compra','uso','ajuste')),
  quantidade integer not null,
  saldo_apos integer not null,
  descricao text not null default '',
  criado_em timestamptz not null default now()
);

create index if not exists idx_ct_user on public.credito_transacoes (user_id);
create index if not exists idx_ct_criado on public.credito_transacoes (criado_em desc);

-- ---------------------------------------------------------------------------
-- 4) Pedidos de pagamento via PIX (liberação manual)
-- ---------------------------------------------------------------------------
create table if not exists public.pedidos_pix (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  plano_id bigint not null references public.planos (id),
  valor_centavos integer not null,
  creditos integer not null,
  referencia text not null,
  status text not null default 'aguardando'
    check (status in ('aguardando','aprovado','recusado','expirado')),
  observacao text not null default '',
  criado_em timestamptz not null default now(),
  aprovado_em timestamptz
);

create index if not exists idx_pp_status on public.pedidos_pix (status, criado_em desc);
create index if not exists idx_pp_user on public.pedidos_pix (user_id);

-- ---------------------------------------------------------------------------
-- 5) Trigger: cria perfil automaticamente no cadastro e concede bônus inicial
-- ---------------------------------------------------------------------------
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.perfis (user_id, nome, groq_api_key, groq_model, credito_inicial)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'nome', new.email),
    coalesce(new.raw_user_meta_data->>'groq_api_key', ''),
    coalesce(new.raw_user_meta_data->>'groq_model', 'openai/gpt-oss-120b'),
    coalesce(new.raw_user_meta_data->>'credito_inicial', '15')::integer
  );
  return new;
end $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ---------------------------------------------------------------------------
-- 6) Função: consome créditos de forma atômica (chamada antes de cada uso de IA)
--    Retorna o saldo restante ou lança erro quando não há créditos.
-- ---------------------------------------------------------------------------
create or replace function public.consumir_creditos(p_qtd integer default 1)
returns integer
language plpgsql
security definer set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_saldo integer;
begin
  if v_uid is null then
    raise exception 'Usuário não autenticado';
  end if;
  if p_qtd is null or p_qtd <= 0 then
    raise exception 'Quantidade de créditos inválida';
  end if;

  update public.perfis
     set credito_inicial = credito_inicial - p_qtd,
         atualizado_em = now()
   where user_id = v_uid
     and credito_inicial >= p_qtd
  returning credito_inicial into v_saldo;

  if v_saldo is null then
    select credito_inicial into v_saldo from public.perfis where user_id = v_uid;
    if v_saldo is null then
      raise exception 'Perfil não encontrado';
    end if;
    raise exception 'CREDITOS_INSUFICIENTES:%', v_saldo;
  end if;

  insert into public.credito_transacoes (user_id, tipo, quantidade, saldo_apos, descricao)
  values (v_uid, 'uso', -p_qtd, v_saldo, 'Uso de IA');
  return v_saldo;
end $$;

grant execute on function public.consumir_creditos(integer) to authenticated;

-- ---------------------------------------------------------------------------
-- 7) Função: aprova/recusa um pedido PIX e credita os créditos (apenas admin)
-- ---------------------------------------------------------------------------
create or replace function public.aprovar_pedido_pix(p_pedido_id bigint, p_aprovar boolean, p_obs text default '')
returns boolean
language plpgsql
security definer set search_path = public
as $$
declare
  v_pedido record;
  v_admin boolean;
  v_saldo integer;
begin
  select is_admin into v_admin from public.perfis where user_id = auth.uid();
  if not coalesce(v_admin, false) then
    raise exception 'Sem permissão de administrador';
  end if;

  select * into v_pedido
    from public.pedidos_pix
   where id = p_pedido_id
   for update;

  if v_pedido is null then
    raise exception 'Pedido não encontrado';
  end if;
  if v_pedido.status <> 'aguardando' then
    raise exception 'Pedido já foi processado';
  end if;

  update public.pedidos_pix
     set status = case when p_aprovar then 'aprovado' else 'recusado' end,
         observacao = p_obs,
         aprovado_em = case when p_aprovar then now() else aprovado_em end
   where id = p_pedido_id;

  if p_aprovar then
    update public.perfis
       set credito_inicial = credito_inicial + v_pedido.creditos,
           atualizado_em = now()
     where user_id = v_pedido.user_id
    returning credito_inicial into v_saldo;
    insert into public.credito_transacoes (user_id, tipo, quantidade, saldo_apos, descricao)
    values (v_pedido.user_id, 'compra', v_pedido.creditos, v_saldo,
            'Pagamento PIX ' || v_pedido.referencia);
  end if;
  return true;
end $$;

grant execute on function public.aprovar_pedido_pix(bigint, boolean, text) to authenticated;

-- ---------------------------------------------------------------------------
-- 8) Função: ajuste manual de créditos (admin) — bônus/correção
-- ---------------------------------------------------------------------------
create or replace function public.ajustar_creditos(p_user_id uuid, p_qtd integer, p_descricao text default '')
returns integer
language plpgsql
security definer set search_path = public
as $$
declare
  v_admin boolean;
  v_saldo integer;
begin
  select is_admin into v_admin from public.perfis where user_id = auth.uid();
  if not coalesce(v_admin, false) then
    raise exception 'Sem permissão de administrador';
  end if;

  update public.perfis
     set credito_inicial = greatest(0, credito_inicial + p_qtd),
         atualizado_em = now()
   where user_id = p_user_id
  returning credito_inicial into v_saldo;

  insert into public.credito_transacoes (user_id, tipo, quantidade, saldo_apos, descricao)
  values (p_user_id, 'ajuste', p_qtd, v_saldo, coalesce(p_descricao, 'Ajuste manual'));

  return v_saldo;
end $$;

grant execute on function public.ajustar_creditos(uuid, integer, text) to authenticated;

-- ---------------------------------------------------------------------------
-- 8b) Função: lista pedidos PIX pendentes (admin) com e-mail e nome do usuário
-- ---------------------------------------------------------------------------
create or replace function public.listar_pedidos_pendentes()
returns table (
  pedido_id bigint,
  referencia text,
  status text,
  valor_centavos integer,
  creditos integer,
  plano_nome text,
  criado_em timestamptz,
  user_email text,
  user_nome text
)
language plpgsql
security definer set search_path = public
as $$
begin
  if not exists (select 1 from public.perfis where user_id = auth.uid() and is_admin) then
    raise exception 'Sem permissão de administrador';
  end if;
  return query
    select pp.id, pp.referencia, pp.status, pp.valor_centavos, pp.creditos,
           pl.nome, pp.criado_em, u.email, pf.nome
      from public.pedidos_pix pp
      join public.planos pl on pl.id = pp.plano_id
      join auth.users u on u.id = pp.user_id
      join public.perfis pf on pf.user_id = pp.user_id
     where pp.status = 'aguardando'
     order by pp.criado_em asc;
end $$;

grant execute on function public.listar_pedidos_pendentes() to authenticated;

-- ---------------------------------------------------------------------------
-- 8c) Função: lista usuários e saldos (admin)
-- ---------------------------------------------------------------------------
create or replace function public.listar_usuarios_admin()
returns table (
  user_id uuid,
  nome text,
  email text,
  unidade text,
  credito_inicial integer,
  groq_model text,
  is_admin boolean,
  criado_em timestamptz
)
language plpgsql
security definer set search_path = public
as $$
begin
  if not exists (select 1 from public.perfis where user_id = auth.uid() and is_admin) then
    raise exception 'Sem permissão de administrador';
  end if;
  return query
    select pf.user_id, pf.nome, u.email, pf.unidade, pf.credito_inicial,
           pf.groq_model, pf.is_admin, pf.criado_em
      from public.perfis pf
      join auth.users u on u.id = pf.user_id
     order by pf.criado_em desc;
end $$;

grant execute on function public.listar_usuarios_admin() to authenticated;

-- ---------------------------------------------------------------------------
-- 9) Row Level Security (RLS)
-- ---------------------------------------------------------------------------
alter table public.perfis enable row level security;
alter table public.credito_transacoes enable row level security;
alter table public.pedidos_pix enable row level security;

drop policy if exists "perfis_le_proprio" on public.perfis;
create policy "perfis_le_proprio"
  on public.perfis for select
  using (auth.uid() = user_id or is_admin);

drop policy if exists "perfis_atualiza_proprio" on public.perfis;
create policy "perfis_atualiza_proprio"
  on public.perfis for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "transacoes_le_proprio" on public.credito_transacoes;
create policy "transacoes_le_proprio"
  on public.credito_transacoes for select
  using (auth.uid() = user_id or exists (
    select 1 from public.perfis p where p.user_id = auth.uid() and p.is_admin
  ));

drop policy if exists "pedidos_le_proprio" on public.pedidos_pix;
create policy "pedidos_le_proprio"
  on public.pedidos_pix for select
  using (auth.uid() = user_id or exists (
    select 1 from public.perfis p where p.user_id = auth.uid() and p.is_admin
  ));

drop policy if exists "pedidos_insere_proprio" on public.pedidos_pix;
create policy "pedidos_insere_proprio"
  on public.pedidos_pix for insert
  with check (auth.uid() = user_id);

-- planos é público (somente pacotes ativos)
alter table public.planos enable row level security;
drop policy if exists "planos_le" on public.planos;
create policy "planos_le"
  on public.planos for select
  using (ativo = true);